### ISSUE TITLE
Package is being compiled with C, it doesn't require that now?

### ISSUE THREAD

**Issue by darynwhite** [conda-forge/plotly-resampler-feedstock#41]
### Comment:

With the addition of `tsdownsample`, I believe there is no need for this package to be compiled. This package, via `pypi`,  easily runs on my macOS ARM chipset, but the package here is being compiled in a way that won't allow for it to install.

Is it necessary to build this with `C` still?

See release notes for 0.9.0 > https://github.com/predict-idlab/plotly-resampler/releases/tag/v0.9.0

**Comment by darynwhite** [comment]
Specifically, these lines:

https://github.com/conda-forge/plotly-resampler-feedstock/blob/3914f4e69ec28970b35af4a2f148faac4c1ab97a/recipe/meta.yaml#L19-L21

**Comment by thewchan** [comment]
Oh, possibly? We can try to see if we can go back to noarch.

**Comment by thewchan** [comment]
Mostly now we need to figure out how to deal with these Python version dependent pins for numpy I think.

**Comment by darynwhite** [comment]
Yeah... Poetry is killing us on that one...

**Comment by darynwhite** [comment]
I've attempted to adapt the pyproject.toml file into the recipe/meta.yaml file here: https://github.com/darynwhite/plotly-resampler-feedstock/blob/main/recipe/meta.yaml

**Comment by thewchan** [comment]
We cannot do that for noarch.

**Comment by darynwhite** [comment]
So I can learn a bit more about conda-forge feedstocks, could you explain, briefly, why it won't work?

**Comment by thewchan** [comment]
We can make it work without using `noarch`, which is when the package has not architecture-dependency requirements. This saves a lot more resource as Conda will build purely python package as intended. A side effect of this is that there can't be also dependencies that varies with different versions of Python, because then technically there can't just be 1 binaries that work for all intended environments. We can remove noarch and use the `numpy` dependencies as specified in `pyproject.toml` but then we'll need to do a matrix build that uses a lot more resource. It's win some lose some I'm afarid.

**Comment by darynwhite** [comment]
Thanks for explaining this!

I was testing different sets of things for the `recipe/meta.yaml` locally yesterday and noticed the matrix build until setting `noarch: python` and removing the second `numpy` requirement. Your explanation makes it all clear to me.
